---
 - name: Create new instance
   hosts: localhost
   gather_facts: False
   vars:
     key_name: Amazon
     group: launch-wizard-4
     instance_type: t2.micro
     image: ami-6df1e514
     wait: yes
     count: 1
     assign_public_ip: yes
     vpc_subnet_id: subnet-8301b0d8
     region: us-west-2
   tasks:
     - name: creating ec2 instance
       ec2:
           key_name: "{{ key_name }}"
           instance_type: "{{ instance_type }}"
           image: "{{ image }}"
           wait: "{{ wait }}"
           group: "{{ group }}"
           count: "{{ count }}"
           vpc_subnet_id: "{{ vpc_subnet_id }}"
           assign_public_ip: "{{ assign_public_ip }}"
           region: "{{ region }}"
